# Instructor Guide {-}

## Suggested Activity Context {-}

**Course Audience**  

- Undergraduate biology majors
- Graduate students with less exposure to bioinformatics

**Course Prerequisites**  

- Layman understanding of genetics (understanding of DNA, genes, trait inheritance)
- Some previous exposure to graphing

**Class Type**  

- Lab
- Computer-based

**Class Size**  

- 1-50

**Lesson Duration**  

Coming soon!

**Assessment Type**  

- Short answer questions at each lab stage

## Lesson Plan  {-}

Coming soon!

## Notes for Instructors {-}

This R-based activity can be run on a different platform, such as your own personal installation of [R](https://www.r-project.org/) or [Posit](https://posit.co/)(formerly called RStudio), depending on your needs. 

More Coming soon!

## Getting Credit for Professional Development {-}

We are happy to provide a letter to your supervisor, department head, or dean to indicate you've worked through this content and intend to use it in your class.